grails:
    profile: plugin
    codegen:
        defaultPackage: grails.trello
    spring:
        transactionManagement:
            proxies: false
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

trello:
  date:
    format: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"

environments:
    development:
      trello:
        apiKey: '767eb76839c0c9afd7ce1d7d2fb1c22f'
        oauthToken: 'bcab1341063eee58da81b79e5d1e93d2b83feb9003ce2a83290042c33886832f'
    test:
      trello:
        apiKey: '767eb76839c0c9afd7ce1d7d2fb1c22f'
        oauthToken: 'bcab1341063eee58da81b79e5d1e93d2b83feb9003ce2a83290042c33886832f'

